version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
